### PR TITLE
➕ Add ESLint

### PR DESCRIPTION
**Pull request by JuKahl**
- Installed ESlint with`npm install eslint --save-dev` 
- Create config with `npx eslint --init`
- Add prettier config
- Solve linter warnings
- Add Next.js typings

https://eslint.org/docs/user-guide/getting-started

### CODE REVIEW

**Review by lmachens — APPROVED** [review]
🚀

**Review by saschahaselhuhn — APPROVED** [review]
gj

**Review by M-Sieger — APPROVED** [review]
lgtm !

**Review by m-wiemers — APPROVED** [review]
perfect job from a perfect guy 👦

**Pull request merged**
