### PR TITLE
✨ Add custom server

### PR DESCRIPTION
**Pull request by JuKahl**
A custom server supports consistent connections with web sockets or databases and allows custom routing.

- Added server folder with server/index.ts. This is the server entry point with a custom route for /storybook to allow a deployment of the app and storybook on a single server. All other requests are forwarded to next request handler.
- Installed new dev script with `npm i -D nodemon ts-node`.
- Added `tsconfig.server.json` for a custom TypeScript config for the server side. The existing tsconfig is extended, but it's required to change the module.
- Added `nodemon.json` to configure nodemon. The server folder is watched.
- Addded and updated `dev`, `build-next`, `build-server`, `build` & `start` scripts.

`npm run dev` is used in development with hot module replacement.
`npm run build` creates optimized client, storybook and server builds.
`npm start` calls the server build.

> A custom server can not be deployed on Vercel, the platform Next.js was made for.

https://nextjs.org/docs/advanced-features/custom-server
https://github.com/vercel/next.js/tree/canary/examples/custom-server-typescript

### CODE REVIEW

**Review by fgottesmann — APPROVED** [review]
Good Job!

**Review by RonjaMeinecke — APPROVED** [review]
well done 👊🏼

**Review by christophvogel — APPROVED** [review]
GJ 💯

**Review by m-wiemers — APPROVED** [review]
This is exactly what I have been looking for all my life ☀🌞

**Review by fre-ben — APPROVED** [review]
Made my day! 🌞

**Review by cboenke — APPROVED** [review]
LGTM 🚀

**Comment by DNaunin** [comment]
Good Job! 🚀

**Comment by SilviaBarcellini** [comment]
All good! 👍

**Pull request merged**
