### PR TITLE
➕ Add TypeScript

### PR DESCRIPTION
**Pull request by JuKahl**
- Added empty ` tsconfig.json`
- Installed TypeScript with `npm install --save-dev typescript @types/react @types/node`
- Reformatted `hello.js, _app.js, index.tsx` to typescript

https://nextjs.org/learn/excel/typescript/nextjs-types

### CODE REVIEW

**Comment by mewiemers** [comment]
are the files _app.js, hello.js and index.js not deleted?

**Review by RonjaMeinecke — APPROVED** [review]
lgtm🚀

**Comment by DNaunin** [comment]
Good Job! 🚀

**Review by lmachens — CHANGES_REQUESTED** [review]
This branch doesn't include the changes of your prettier branch. I guess you forgot to pull the latest changes in `main` branch before creating this `typescript` branch. 
That's why you have merge conflicts.

After you fixed the conflicts, make sure to format all new files like `tsconfig.json`.

**Review by m-wiemers — APPROVED** [review]
It looks better like this

**Review by sweisz — APPROVED** [review]
👍

**Pull request merged**
