### PR TITLE
➕ Add storybook

### PR DESCRIPTION
**Pull request by JuKahl**
- Installed storybook with `npx sb init`
- Removed example stories folder
- Created `components` folder with example Button component
- Set stories folder in `.storybook/main.js`
- Loaded example component in `pages/index.tsx`
- Ignored `/storybook-static`
- Added `.eslintignore`

https://storybook.js.org/docs/react/get-started/install

### CODE REVIEW

**Review by saschahaselhuhn — APPROVED** [review]
gj

**Review by christophvogel — APPROVED** [review]
GJ 👍

**Review by RonjaMeinecke — APPROVED** [review]
LGTM👊🏼

**Comment by SilviaBarcellini** [comment]
All good 👍

**Review by cboenke — APPROVED** [review]
LGTM 🚀

**Review by m-wiemers — APPROVED** [review]
What a pity that I am not you 😢

**Review by sweisz — APPROVED** [review]
LGTM 👍

**Pull request merged**
